<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // Array prodotti ristoranti, già associato l'id del ristorante
        $products = [
            [
                'nome' => 'Pizza Margherita',
                'descrizione' => 'Pizza classica con pomodoro, mozzarella e basilico.',
                'ingredienti' => 'Pomodoro, mozzarella, basilico',
                'prezzo' => 5.99,
                'is_visible' => true,
                'image' => 'pizza-margherita.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Antipasto di mare',
                'descrizione' => 'Un saporito mix di polpi, gamberetti e seppie',
                'ingredienti' => 'Polpo, Gamberetti, Seppie, Patate, Sedano, Olio, Aceto, Prezemolo',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Antipasto-mare-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Antipasto di terra',
                'descrizione' => 'Un mix di vari salumi del posto',
                'ingredienti' => 'Salsiccia, Salame, Prosciutto, Coppa, Pancetta, Formaggio, Olive',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'Antipasto-terra-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Mozzarella in carrozza',
                'descrizione' => 'Mozarella fresca fritta e ricoperta di bricciole di pane',
                'ingredienti' => 'Mozzarella, Pane integrale, Pomodoro, Origano',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Mozzarella-carr-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Gamberoni allo spiedo',
                'descrizione' => 'Una grigliata di gamberoni',
                'ingredienti' => 'Gamberoni, Prezemolo, Aglio',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Gamberoni-griglia-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Arrabbiata',
                'descrizione' => 'Pasta con un condimento piccante',
                'ingredienti' => "Penne, N'duja, Salsiccia, Pomodoro, Chili",
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Arrabiata-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Bolognese',
                'descrizione' => 'Pasta con un delicato ragù di manzo',
                'ingredienti' => 'Penne, Manzo, Pomodoro, Basilico',
                'prezzo' => 6.50,
                'is_visible' => true,
                'image' => 'Bolognese-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Carbonara',
                'descrizione' => 'Pasta con uova e guanciale',
                'ingredienti' => 'Spaghetti, Uova, Guanciale, Peppe, Cipolla',
                'prezzo' => 5.50,
                'is_visible' => true,
                'image' => 'Carbonara-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Boscaiola',
                'descrizione' => 'La pizza dei boschi',
                'ingredienti' => 'Prosciutto, Funghi, Pomodoro, Mozzarella, Origano',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Boscaiola-pizza-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Diavola',
                'descrizione' => 'La preferita di Lucifero',
                'ingredienti' => 'Salame piccante, Olive nere, Pomidoro, Mozzarella, Farina',
                'prezzo' => 10.00,
                'is_visible' => true,
                'image' => 'Diavola-pizza-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Vegetariana',
                'descrizione' => 'Pizza per erbivori',
                'ingredienti' => 'Melanzane, Zucchine, Pomodoro, Mozzarella, Funghi',
                'prezzo' => 7.50,
                'is_visible' => true,
                'image' => 'Vegetariana-pizza-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Grigliatta mix max',
                'descrizione' => 'Mix di carni alla griglia',
                'ingredienti' => 'Manzo, Maiale, Pollo, Pecora',
                'prezzo' => 19.99,
                'is_visible' => true,
                'image' => 'Grigliatta-mix-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Polenta proteica',
                'descrizione' => 'Polenta con carne',
                'ingredienti' => 'Polenta, Manzo, Salsiccia',
                'prezzo' => 4.99,
                'is_visible' => true,
                'image' => 'Polenta-carne-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Polenta fibrosa',
                'descrizione' => 'Polenta con verdure',
                'ingredienti' => 'Polenta, Funghi, Carotte',
                'prezzo' => 4.99,
                'is_visible' => true,
                'image' => 'Polenta-verdure-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Risotto marino',
                'descrizione' => 'Un risotto con pesce',
                'ingredienti' => 'Riso, Merluzzo, Gamberi, Prezzemolo, Peperoncino',
                'prezzo' => 6.66,
                'is_visible' => true,
                'image' => 'Risotto-mare-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Tortellini',
                'descrizione' => 'Tortellini in brodo',
                'ingredienti' => 'Tortellini, Brodo di manzo, Maiale',
                'prezzo' => 7.60,
                'is_visible' => true,
                'image' => 'Tortellini-carne-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Lasagne',
                'descrizione' => 'Lasagne al forno',
                'ingredienti' => 'Pasta, Manzo, Pomodoro, Besciamella',
                'prezzo' => 8.20,
                'is_visible' => true,
                'image' => 'Lasagne-primo-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Torta di pinoli',
                'descrizione' => 'Una torta aberrantemente deliziosa?',
                'ingredienti' => 'Farina, Uova, Pinoli, Frutta secca varia',
                'prezzo' => 8.88,
                'is_visible' => true,
                'image' => 'Torta-pinolata-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Torta di mele',
                'descrizione' => 'Una fetta di torta con panna',
                'ingredienti' => 'Farina, Uova, Mele, Panna, Zucchero',
                'prezzo' => 4.60,
                'is_visible' => true,
                'image' => 'Torta-melosa-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Tiramisù',
                'descrizione' => 'Una mano per quando si è giù',
                'ingredienti' => 'Mascarpone, Uova, Latte, Zucchero, Caccao',
                'prezzo' => 6.40,
                'is_visible' => true,
                'image' => 'Tiramisu-dolce-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Risotto ai Funghi',
                'descrizione' => 'Piatto italiano con riso, funghi porcini e formaggio parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, formaggio parmigiano',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'Risotto-ai-funghi.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Hamburger Messicano',
                'descrizione' => 'Hamburger con chili, guacamole e jalapeños piccanti.',
                'ingredienti' => 'Carne, chili, guacamole, jalapeños',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'hamburger-vegetariano.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Taco al Pastor',
                'descrizione' => 'Taco messicano con carne di maiale marinata e ananas.',
                'ingredienti' => 'Carne di maiale, ananas, cipolle',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'taco.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Tortillas',
                'descrizione' => 'Una spianata arrotolata con il mondo dentro',
                'ingredienti' => 'Spianata, Maiale, Peperone, Insalata, Pomodoro, Halapeno, Patate, Olive, Melanzane, Zucchine, Funghi',
                'prezzo' => 2.99,
                'is_visible' => true,
                'image' => 'Tortilla-mundo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Fajitas de pollo',
                'descrizione' => 'Rondelle di spianata con pollo',
                'ingredienti' => 'Fajitas, Pollo, Panna acida, Arachidi, Menta, Peperoncino',
                'prezzo' => 4.30,
                'is_visible' => true,
                'image' => 'Fajitas-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Insalata di fagioli',
                'descrizione' => 'Una fresca insalata piccante',
                'ingredienti' => 'Fagioli, Mais, Insalata, Peperoni, Peperoncino',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Insalata-fagioli-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Ali di pollo',
                'descrizione' => 'Alette di pollo marinate e grigliate',
                'ingredienti' => 'Pollo, Rosmarino, Peperoncino, Peperone, Olio piccante',
                'prezzo' => 6.66,
                'is_visible' => true,
                'image' => 'Ali-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Nachos',
                'descrizione' => 'Un contorno di nachos e salsa mix',
                'ingredienti' => 'Nachos, Formaggio, Guacamole, Salsa piccante',
                'prezzo' => 5.55,
                'is_visible' => true,
                'image' => 'Nachos-contorno-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Burrito',
                'descrizione' => 'Un imbottitura deliziosa avvolta da una spianata',
                'ingredienti' => 'Spianata, Maiale, Manzo, Pollo, Peperonciono, Olive, Peperone',
                'prezzo' => 4.60,
                'is_visible' => true,
                'image' => 'Burrito-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Chimichanga',
                'descrizione' => 'Tortillas fritte',
                'ingredienti' => 'Tortillas, Maiale, Pollo, Fagioli',
                'prezzo' => 6.70,
                'is_visible' => true,
                'image' => 'Chimichanga-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Coq au Vin',
                'descrizione' => 'Piatto francese con pollo cotto nel vino rosso con funghi e cipolle.',
                'ingredienti' => 'Pollo, vino rosso, funghi, cipolle',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => '',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Noodles al Curry Verde',
                'descrizione' => 'Noodles tailandesi in salsa di curry verde con gamberetti e verdure.',
                'ingredienti' => 'Noodles, curry verde, gamberetti, verdure',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => "Anatra all'arancia",
                'descrizione' => 'Anatra con arance aromatizzanti',
                'ingredienti' => 'Anatra, Arancia, Rosmarino',
                'prezzo' => 8.90,
                'is_visible' => true,
                'image' => 'Anatra-arancia-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Riso alla cantonese',
                'descrizione' => 'Riso con piselli',
                'ingredienti' => 'Riso, Uova, Piselli, Pancetta',
                'prezzo' => 8.40,
                'is_visible' => true,
                'image' => 'Riso-cantonese-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Maiale in agrodolce',
                'descrizione' => 'Maiale insaporito con erbe e salsa agrodolce',
                'ingredienti' => 'Maiale, Salsa agrodolce, Rosmarino, Salvia',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'Maiale-agrodolce-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Cosce di rana',
                'descrizione' => 'Rane fritte, ma solo cosce, niente petto',
                'ingredienti' => 'Rane, Farina, Olio',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Rane-fritte-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Ravioli al vapore',
                'descrizione' => 'Delicati e profumati ravioli al vapore',
                'ingredienti' => 'Farina, Maiale, Cumino, Riso',
                'prezzo' => 4.33,
                'is_visible' => true,
                'image' => 'Ravioli-vapore-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Edamame',
                'descrizione' => 'Edamame',
                'ingredienti' => 'Edamame',
                'prezzo' => 7.45,
                'is_visible' => true,
                'image' => 'Edamame-edamame-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Pollo al curry',
                'descrizione' => 'Pollo con curry',
                'ingredienti' => 'Pollo, Curry, Cumino, Curcume, Chiodi di garofano, Roux',
                'prezzo' => 4.70,
                'is_visible' => true,
                'image' => 'Pollo-curry-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Ramen al Tonkotsu',
                'descrizione' => 'Zuppa giapponese con noodles al tonkotsu e maiale.',
                'ingredienti' => 'Noodles, brodo di maiale, maiale cotto',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese-ramen.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Tempura Misto',
                'descrizione' => 'Tempura giapponese con gamberi, verdure e salsa dipping.',
                'ingredienti' => 'Gamberi, verdure, salsa dipping',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => '',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Sushi Sashimi Deluxe',
                'descrizione' => 'Assortimento di sushi e sashimi giapponese con pesce fresco.',
                'ingredienti' => 'Pesce crudo, riso, alga nori',
                'prezzo' => 18.99,
                'is_visible' => true,
                'image' => 'sushi.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Croissant al Cioccolato',
                'descrizione' => 'Pasticcino francese ripieno di cioccolato fondente.',
                'ingredienti' => 'Farina, burro, cioccolato fondente',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Croissan.jpg',
                'restaurant_id' => 6,
            ],
            [
                'nome' => 'Ratatouille',
                'descrizione' => 'Piatto francese a base di verdure come melanzane, zucchine e pomodori.',
                'ingredienti' => 'Melanzane, zucchine, pomodori',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'cibo-francese.jpg',
                'restaurant_id' => 6,
            ],
            [
                'nome' => 'Pad Thai',
                'descrizione' => 'Piatto tailandese con noodles, gamberetti, uova e arachidi.',
                'ingredienti' => 'Noodles, gamberetti, uova, arachidi',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese.jpg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Paneer Tikka',
                'descrizione' => 'Antipasto indiano con cubetti di formaggio marinato e grigliato.',
                'ingredienti' => 'Formaggio paneer, spezie, yogurt',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'cibo-messicano.jpeg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Dolce al Mango',
                'descrizione' => 'Dolce tailandese con mango, riso glutinoso e latte di cocco.',
                'ingredienti' => 'Mango, riso glutinoso, latte di cocco',
                'prezzo' => 6.99,
                'is_visible' => true,
                'image' => 'piatto-indiano.jpg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Dal Makhani',
                'descrizione' => 'Piatto indiano a base di lenticchie nere e spezie.',
                'ingredienti' => 'Lenticchie nere, spezie, panna',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'cibo-indiano-lenticchie.jpeg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Misto di carne',
                'descrizione' => 'Fettina, sovracoscia, bombette e spiedini con contorno melanzane, zucchine, pomodori, sedano, noci e maionese.',
                'ingredienti' => 'Fettina, sovracoscia, bombette e spiedini',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'carne.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Risotto ai Funghi',
                'descrizione' => 'Piatto italiano con riso, funghi porcini e formaggio parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, formaggio parmigiano',
                'prezzo' => 35.99,
                'is_visible' => true,
                'image' => 'Risotto-ai-funghi.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Lasagna al Forno',
                'descrizione' => 'Uno strato di pasta al forno ricoperto di ricotta, carne macinata, pomodoro e formaggio fuso.',
                'ingredienti' => 'Pasta, carne macinata, ricotta, pomodoro, formaggio',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'lasagna.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Pizza Margherita',
                'descrizione' => 'Una pizza classica italiana con mozzarella, pomodoro e basilico.',
                'ingredienti' => 'Mozzarella, pomodoro, basilico',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'pizza_margherita.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Risotto ai Funghi Porcini',
                'descrizione' => 'Risotto cremoso preparato con funghi porcini freschi e parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, brodo, parmigiano',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'risotto_funghi.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Penne alla Vodka',
                'descrizione' => 'Penne in una salsa cremosa a base di vodka, pomodoro e panna.',
                'ingredienti' => 'Penne, vodka, pomodoro, panna',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'penne_vodka.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Ossobuco alla Milanese',
                'descrizione' => 'Un piatto milanese tradizionale con stinco di vitello cotto in una salsa ricca.',
                'ingredienti' => 'Stinco di vitello, vino bianco, brodo, gremolata',
                'prezzo' => 24.99,
                'is_visible' => true,
                'image' => 'ossobuco.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tiramisù',
                'descrizione' => 'Un dolce italiano classico con biscotti savoiardi, caffè, mascarpone e cacao.',
                'ingredienti' => 'Savoiardi, caffè, mascarpone, cacao',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'tiramisu.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tagliatelle al Tartufo',
                'descrizione' => 'Tagliatelle fresche condite con una salsa al tartufo nero prelibata.',
                'ingredienti' => 'Tagliatelle, tartufo nero, panna, burro',
                'prezzo' => 19.99,
                'is_visible' => true,
                'image' => 'tagliatelle_tartufo.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Calamari Fritti',
                'descrizione' => 'Calamari freschi fritti in una crosta croccante, serviti con salsa al limone.',
                'ingredienti' => 'Calamari, farina, olio, limone',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'calamari_fritti.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Ravioli al Burro e Salvia',
                'descrizione' => 'Ravioli ripieni di ricotta e spinaci, conditi con burro fuso e salvia.',
                'ingredienti' => 'Ravioli, ricotta, spinaci, burro, salvia',
                'prezzo' => 15.99,
                'is_visible' => true,
                'image' => 'ravioli_burro_salvia.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tofu al Curry',
                'descrizione' => 'Piatto vegetariano con tofu, verdure e curry.',
                'ingredienti' => 'Tofu, verdure, curry',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'piatto-indiano.jpg',
                'restaurant_id' => 9,
            ],
            [
                'nome' => 'Insalata Waldorf',
                'descrizione' => 'Insalata classica con mele, sedano, noci e maionese.',
                'ingredienti' => 'Mele, sedano, noci, maionese',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'insalata.jpg',
                'restaurant_id' => 9,
            ],
            [
                'nome' => 'Sushi Vegano',
                'descrizione' => 'Assortimento di sushi vegano con avocado, cetriolo e pepe.',
                'ingredienti' => 'Avocado, cetriolo, pepe',
                'prezzo' => 15.99,
                'is_visible' => true,
                'image' => 'sushi.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Hamburger Vegetariano',
                'descrizione' => 'Hamburger vegetariano con pattina di ceci e verdure.',
                'ingredienti' => 'Pattina di ceci, verdure, pane vegano',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'hamburger-vegetariano.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Bowl di Quinoa e Verdure',
                'descrizione' => 'Un bowl salutare con quinoa, verdure miste, ceci e una vinaigrette al limone.',
                'ingredienti' => 'Quinoa, verdure miste, ceci, limone',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'bowl_quinoa.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Pizza Vegana ai Funghi',
                'descrizione' => 'Una pizza vegana con base di verdure, funghi misti, e formaggio vegano.',
                'ingredienti' => 'Base di verdure, funghi misti, formaggio vegano',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'pizza_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Hamburger di Ceci',
                'descrizione' => 'Un hamburger a base di ceci con insalata, pomodoro e maionese vegana.',
                'ingredienti' => 'Ceci, insalata, pomodoro, maionese vegana',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'hamburger_ceci.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Avocado e Lenticchie',
                'descrizione' => "Un'insalata fresca con avocado, lenticchie, cetrioli e un dressing al sesamo.",
                'ingredienti' => 'Avocado, lenticchie, cetrioli, dressing al sesamo',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'insalata_avocado.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Pasta al Pesto di Basilico',
                'descrizione' => 'Pasta servita con un pesto cremoso a base di basilico, pinoli e lievito alimentare.',
                'ingredienti' => 'Pasta, pesto di basilico, pinoli, lievito alimentare',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'pasta_pesto.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Quinoa e Avocado',
                'descrizione' => "Un'insalata leggera con quinoa, avocado, pomodori e olive nere.",
                'ingredienti' => 'Quinoa, avocado, pomodori, olive nere',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'insalata_quinoa_avocado.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Risotto ai Funghi Porcini',
                'descrizione' => 'Risotto cremoso preparato con funghi porcini freschi e senza latticini.',
                'ingredienti' => 'Riso, funghi porcini, brodo vegetale',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'risotto_funghi_vegano.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Tacos di Barbabietola',
                'descrizione' => 'Tacos gustosi con barbabietola arrostita, guacamole e salsa piccante.',
                'ingredienti' => 'Barbabietola, guacamole, salsa piccante, tortilla',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'tacos_barbabietola.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Zuppa di Lenticchie Rosse',
                'descrizione' => 'Una zuppa deliziosa a base di lenticchie rosse, pomodori e curry.',
                'ingredienti' => 'Lenticchie rosse, pomodori, curry',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'zuppa_lenticchie_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Frutta Fresca',
                'descrizione' => "Un'insalata rinfrescante con una varietà di frutta fresca e una spruzzata di limone.",
                'ingredienti' => 'Frutta mista, limone',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'insalata_frutta_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Curry Massaman',
                'descrizione' => 'Curry thailandese con carne, patate e arachidi.',
                'ingredienti' => 'Carne, patate, arachidi',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'curry-indiano.jpeg',
                'restaurant_id' => 3,
            ],
        ];

        // Inserisce prodotti nell'array multidimensionale
        Product::insert($products);
    }
}

    
