<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // Array prodotti ristoranti, già associato l'id del ristorante
        $products = [
            [
                'nome' => 'Pizza Margherita',
                'descrizione' => 'Pizza classica con pomodoro, mozzarella e basilico.',
                'ingredienti' => 'Pomodoro, mozzarella, basilico',
                'prezzo' => 5.99,
                'is_visible' => true,
                'image' => 'pizza-margherita.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Antipasto di mare',
                'descrizione' => 'Un saporito mix di polpi, gamberetti e seppie',
                'ingredienti' => 'Polpo, Gamberetti, Seppie, Patate, Sedano, Olio, Aceto, Prezemolo',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Antipasto-mare-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Antipasto di terra',
                'descrizione' => 'Un mix di vari salumi del posto',
                'ingredienti' => 'Salsiccia, Salame, Prosciutto, Coppa, Pancetta, Formaggio, Olive',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'Antipasto-terra-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Mozzarella in carrozza',
                'descrizione' => 'Mozzarella fresca fritta e ricoperta di bricciole di pane',
                'ingredienti' => 'Mozzarella, Pane integrale, Pomodoro, Origano',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Mozzarella-carrozza.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Gamberoni allo spiedo',
                'descrizione' => 'Una grigliata di gamberoni',
                'ingredienti' => 'Gamberoni, Prezemolo, Aglio',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Gamberoni-griglia-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Arrabbiata',
                'descrizione' => 'Pasta con un condimento piccante',
                'ingredienti' => "Penne, N'duja, Salsiccia, Pomodoro, Chili",
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Arrabiata-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Bolognese',
                'descrizione' => 'Pasta con un delicato ragù di manzo',
                'ingredienti' => 'Penne, Manzo, Pomodoro, Basilico',
                'prezzo' => 6.50,
                'is_visible' => true,
                'image' => 'Bolognese-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Carbonara',
                'descrizione' => 'Pasta con uova e guanciale',
                'ingredienti' => 'Spaghetti, Uova, Guanciale, Peppe, Cipolla',
                'prezzo' => 5.50,
                'is_visible' => true,
                'image' => 'Carbonara-pasta-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Diavola',
                'descrizione' => 'La preferita di Lucifero',
                'ingredienti' => 'Salame piccante, Olive nere, Pomidoro, Mozzarella, Farina',
                'prezzo' => 10.00,
                'is_visible' => true,
                'image' => 'Diavola-pizza-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Vegetariana',
                'descrizione' => 'Pizza per erbivori',
                'ingredienti' => 'Melanzane, Zucchine, Pomodoro, Mozzarella, Funghi',
                'prezzo' => 7.50,
                'is_visible' => true,
                'image' => 'Vegetariana-pizza-mario.jpg',
                'restaurant_id' => 1,
            ],
            [
                'nome' => 'Grigliatta mix max',
                'descrizione' => 'Mix di carni alla griglia',
                'ingredienti' => 'Manzo, Maiale, Pollo, Pecora',
                'prezzo' => 19.99,
                'is_visible' => true,
                'image' => 'Grigliatta-mix-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Polenta proteica',
                'descrizione' => 'Polenta con carne',
                'ingredienti' => 'Polenta, Manzo, Salsiccia',
                'prezzo' => 4.99,
                'is_visible' => true,
                'image' => 'Polenta-carne-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Polenta fibrosa',
                'descrizione' => 'Polenta con verdure',
                'ingredienti' => 'Polenta, Funghi, Carotte',
                'prezzo' => 4.99,
                'is_visible' => true,
                'image' => 'Polenta-verdure-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Risotto marino',
                'descrizione' => 'Un risotto con pesce',
                'ingredienti' => 'Riso, Gamberi, Prezzemolo, Peperoncino, Cozze, Vongole',
                'prezzo' => 6.66,
                'is_visible' => true,
                'image' => 'Risotto-mare-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Tortellini',
                'descrizione' => 'Tortellini in brodo',
                'ingredienti' => 'Tortellini, Brodo di manzo, Maiale',
                'prezzo' => 7.60,
                'is_visible' => true,
                'image' => 'Tortellini-carne-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Lasagne',
                'descrizione' => 'Lasagne al forno',
                'ingredienti' => 'Pasta, Manzo, Pomodoro, Besciamella',
                'prezzo' => 8.20,
                'is_visible' => true,
                'image' => 'Lasagne-primo-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Torta di pinoli',
                'descrizione' => 'Una torta aberrantemente deliziosa?',
                'ingredienti' => 'Farina, Uova, Pinoli, Frutta secca varia',
                'prezzo' => 8.88,
                'is_visible' => true,
                'image' => 'Torta-pinolata-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Torta di mele',
                'descrizione' => 'Una fetta di torta con panna',
                'ingredienti' => 'Farina, Uova, Mele, Panna, Zucchero',
                'prezzo' => 4.60,
                'is_visible' => true,
                'image' => 'Torta-melosa-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Tiramisù',
                'descrizione' => 'Una mano per quando si è giù',
                'ingredienti' => 'Mascarpone, Uova, Latte, Zucchero, Caccao',
                'prezzo' => 6.40,
                'is_visible' => true,
                'image' => 'Tiramisu-dolce-trattoria.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Risotto ai Funghi',
                'descrizione' => 'Piatto italiano con riso, funghi porcini e formaggio parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, formaggio parmigiano',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'Risotto-ai-funghi.jpg',
                'restaurant_id' => 2,
            ],
            [
                'nome' => 'Hamburger Messicano',
                'descrizione' => 'Hamburger con chili, guacamole e jalapeños piccanti.',
                'ingredienti' => 'Carne, chili, guacamole, jalapeños',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'hamburger-vegetariano.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Taco al Pastor',
                'descrizione' => 'Taco messicano con carne di maiale marinata e ananas.',
                'ingredienti' => 'Carne di maiale, ananas, cipolle',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'taco.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Tortillas',
                'descrizione' => 'Una spianata arrotolata con il mondo dentro',
                'ingredienti' => 'Spianata, Maiale, Peperone, Insalata, Pomodoro, Halapeno, Patate, Olive, Melanzane, Zucchine, Funghi',
                'prezzo' => 2.99,
                'is_visible' => true,
                'image' => 'Tortilla-mundo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Fajitas de pollo',
                'descrizione' => 'Rondelle di spianata con pollo',
                'ingredienti' => 'Fajitas, Pollo, Panna acida, Arachidi, Menta, Peperoncino',
                'prezzo' => 4.30,
                'is_visible' => true,
                'image' => 'Fajitas-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Insalata di fagioli',
                'descrizione' => 'Una fresca insalata piccante',
                'ingredienti' => 'Fagioli, Cipolla, Insalata, Peperoni, Peperoncino',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Insalata-fagioli-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Ali di pollo',
                'descrizione' => 'Alette di pollo marinate e grigliate',
                'ingredienti' => 'Pollo, Rosmarino, Peperoncino, Peperone, Olio piccante',
                'prezzo' => 6.66,
                'is_visible' => true,
                'image' => 'Ali-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Nachos',
                'descrizione' => 'Un contorno di nachos e salsa mix',
                'ingredienti' => 'Nachos, Formaggio, Guacamole, Salsa piccante',
                'prezzo' => 5.55,
                'is_visible' => true,
                'image' => 'Nachos-contorno-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Burrito',
                'descrizione' => 'Un imbottitura deliziosa avvolta da una spianata',
                'ingredienti' => 'Spianata, Maiale, Manzo, Pollo, Peperonciono, Olive, Peperone',
                'prezzo' => 4.60,
                'is_visible' => true,
                'image' => 'Burrito-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Chimichanga',
                'descrizione' => 'Tortillas fritte',
                'ingredienti' => 'Tortillas, Maiale, Pollo, Fagioli',
                'prezzo' => 6.70,
                'is_visible' => true,
                'image' => 'Chimichanga-secondo-fiesta.jpg',
                'restaurant_id' => 3,
            ],
            [
                'nome' => 'Noodles al Curry Verde',
                'descrizione' => 'Noodles tailandesi in salsa di curry verde con gamberetti e verdure.',
                'ingredienti' => 'Noodles, curry verde, gamberetti, verdure',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => "Anatra all'arancia",
                'descrizione' => 'Anatra con arance aromatizzanti',
                'ingredienti' => 'Anatra, Arancia, Rosmarino',
                'prezzo' => 8.90,
                'is_visible' => true,
                'image' => 'Anatra-arancia-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Riso alla cantonese',
                'descrizione' => 'Riso con piselli',
                'ingredienti' => 'Riso, Uova, Piselli, Prosciutto cotto',
                'prezzo' => 8.40,
                'is_visible' => true,
                'image' => 'Riso-cantonese-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Maiale in agrodolce',
                'descrizione' => 'Maiale insaporito con erbe e salsa agrodolce',
                'ingredienti' => 'Maiale, Salsa agrodolce, Rosmarino, Salvia, Peperoni',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'Maiale-agrodolce-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Cosce di rana',
                'descrizione' => 'Rane fritte, ma solo cosce, niente petto',
                'ingredienti' => 'Rane, Farina, Olio',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Rane-fritte-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Ravioli al vapore',
                'descrizione' => 'Delicati e profumati ravioli al vapore',
                'ingredienti' => 'Farina, Maiale, Cumino, Riso',
                'prezzo' => 4.33,
                'is_visible' => true,
                'image' => 'Ravioli-vapore-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Edamame',
                'descrizione' => 'Edamame',
                'ingredienti' => 'Edamame',
                'prezzo' => 7.45,
                'is_visible' => true,
                'image' => 'Edamame-edamame-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Pollo al curry',
                'descrizione' => 'Pollo con curry',
                'ingredienti' => 'Pollo, Curry, Cumino, Curcume, Chiodi di garofano, Roux',
                'prezzo' => 4.70,
                'is_visible' => true,
                'image' => 'Pollo-curry-wok.jpg',
                'restaurant_id' => 4,
            ],
            [
                'nome' => 'Ramen al Tonkotsu',
                'descrizione' => 'Zuppa giapponese con noodles al tonkotsu e maiale.',
                'ingredienti' => 'Noodles, brodo di maiale, maiale cotto',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese-ramen.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Tempura Misto',
                'descrizione' => 'Tempura giapponese con gamberi, verdure e salsa dipping.',
                'ingredienti' => 'Gamberi, verdure, salsa dipping',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Tempura-Misto.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Sushi Sashimi Deluxe',
                'descrizione' => 'Assortimento di sushi e sashimi giapponese con pesce fresco.',
                'ingredienti' => 'Pesce crudo, riso, alga nori',
                'prezzo' => 18.99,
                'is_visible' => true,
                'image' => 'Sashimi.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Sushi assortito',
                'descrizione' => 'Una selezione di sushi fresco con pesce crudo e riso aromatizzato.',
                'ingredienti' => 'Pesce fresco, riso, alga nori, salsa di soia',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Sushi-assortito.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Tempura di gamberi',
                'descrizione' => 'Gamberi freschi ricoperti di pastella croccante, fritti finemente.',
                'ingredienti' => 'Gamberi, pastella, olio per friggere',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'Tempura.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Ramen al miso',
                'descrizione' => 'Una zuppa di noodle giapponese con brodo al miso e topping assortiti.',
                'ingredienti' => 'Noodle, brodo di miso, uovo, cipolla verde',
                'prezzo' => 10.49,
                'is_visible' => true,
                'image' => 'Ramen.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Sashimi di salmone',
                'descrizione' => 'Fette sottili di salmone crudo, servite con salsa di zenzero e wasabi.',
                'ingredienti' => 'Salmone fresco, salsa di zenzero, wasabi',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Sashimi-salmone.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Unagi Don',
                'descrizione' => 'Un piatto di riso caldo coperto con anguilla glassata e salsa teriyaki.',
                'ingredienti' => 'Riso, anguilla, salsa teriyaki',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'Unagi.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Gyoza al pollo',
                'descrizione' => 'Ravioli giapponesi ripieni di pollo e verdure, cotti al vapore e poi saltati in padella.',
                'ingredienti' => 'Pasta per gyoza, pollo, verdure',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'Gyoza.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Okonomiyaki',
                'descrizione' => 'Una specie di pancake giapponese con ripieno di carne e verdure.',
                'ingredienti' => 'Farina, uova, cavolo, pancetta',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Okonomiyaki.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Takoyaki',
                'descrizione' => 'Palle di polpo fritte, tipiche delle strade giapponesi.',
                'ingredienti' => 'Polpo, pastella, salsa okonomiyaki',
                'prezzo' => 6.49,
                'is_visible' => true,
                'image' => 'Takoyaki.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Sunomono',
                'descrizione' => "Un'insalata giapponese di cetrioli marinati in aceto di riso e alga wakame.",
                'ingredienti' => 'Cetrioli, aceto di riso, alga wakame',
                'prezzo' => 5.99,
                'is_visible' => true,
                'image' => 'Sunomono.jpg',
                'restaurant_id' => 5,
            ],

            [
                'nome' => 'Yakitori',
                'descrizione' => 'Spiedini di pollo alla griglia con salsa teriyaki.',
                'ingredienti' => 'Pollo, salsa teriyaki',
                'prezzo' => 8.49,
                'is_visible' => true,
                'image' => 'Yakitori.jpg',
                'restaurant_id' => 5,
            ],
            [
                'nome' => 'Croissant al Cioccolato',
                'descrizione' => 'Pasticcino francese ripieno di cioccolato fondente.',
                'ingredienti' => 'Farina, burro, cioccolato fondente',
                'prezzo' => 3.99,
                'is_visible' => true,
                'image' => 'Croissan.jpg',
                'restaurant_id' => 6,
            ],
            [
                'nome' => 'Ratatouille',
                'descrizione' => 'Piatto francese a base di verdure come melanzane, zucchine e pomodori.',
                'ingredienti' => 'Melanzane, zucchine, pomodori',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'cibo-francese.jpg',
                'restaurant_id' => 6,
            ],
            [
                'nome' => 'Coq au Vin',
                'descrizione' => 'Un piatto classico francese di pollo cotto lentamente in vino rosso con funghi e cipolle.',
                'ingredienti' => 'Pollo, vino rosso, funghi, cipolle',
                'prezzo' => 18.99,
                'is_visible' => true,
                'image' => 'Coq.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Boeuf Bourguignon',
                'descrizione' => 'Una ricca stufato di manzo cotto in vino rosso con pancetta e cipolle.',
                'ingredienti' => 'Manzo, vino rosso, pancetta, cipolle',
                'prezzo' => 22.99,
                'is_visible' => true,
                'image' => 'Boeuf.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Ratatouille',
                'descrizione' => 'Una deliziosa melanzane, peperoni, zucchine e pomodori in umido, tipica del sud della Francia.',
                'ingredienti' => 'Melanzane, peperoni, zucchine, pomodori',
                'prezzo' => 14.49,
                'is_visible' => true,
                'image' => 'Ratatouille.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Quiche Lorraine',
                'descrizione' => 'Una torta salata con pancetta e formaggio, originaria della regione della Lorena.',
                'ingredienti' => 'Pancetta, formaggio, uova',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Quiche.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Escargot',
                'descrizione' => 'Lumache cotte in burro, aglio e prezzemolo, servite in gusci.',
                'ingredienti' => 'Lumache, burro, aglio, prezzemolo',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'Escargot.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Soupe à l’Oignon',
                'descrizione' => 'Zuppa di cipolle gratinata con crostini di pane e formaggio.',
                'ingredienti' => 'Cipolle, brodo di carne, pane, formaggio',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'Soupe.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Bouillabaisse',
                'descrizione' => 'Una zuppa di pesce tradizionale con varietà di pesce e crostacei.',
                'ingredienti' => 'Pesce, crostacei, pomodori, erbe aromatiche',
                'prezzo' => 20.99,
                'is_visible' => true,
                'image' => 'Bouillabaisse.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Cassoulet',
                'descrizione' => "Un piatto ricco e saporito con fagioli, salsiccia e carne d'anatra o maiale.",
                'ingredienti' => "Fagioli, salsiccia, carne d'anatra, maiale",
                'prezzo' => 19.49,
                'is_visible' => true,
                'image' => 'Cassoulet.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => 'Tarte Tatin',
                'descrizione' => 'Una crostata di mele caramellate rovesciata con un guscio di pasta sfoglia.',
                'ingredienti' => 'Mele, zucchero, pasta sfoglia',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'Tarte.jpg',
                'restaurant_id' => 6,
            ],

            [
                'nome' => "Duck à l'Orange",
                'descrizione' => "Anatra arrosto con salsa all'arancia dolce e amara.",
                'ingredienti' => 'Anatra, arancia, zucchero',
                'prezzo' => 24.99,
                'is_visible' => true,
                'image' => 'Duck.jpg',
                'restaurant_id' => 6,
            ],
            [
                'nome' => 'Pad Thai',
                'descrizione' => 'Piatto tailandese con noodles, gamberetti, uova e arachidi.',
                'ingredienti' => 'Noodles, gamberetti, uova, arachidi',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'zuppa-giapponese.jpg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Tandoori Chicken',
                'descrizione' => 'Pollo marinato in spezie e yogurt, cotto in un forno tandoor.',
                'ingredienti' => 'Pollo, yogurt, spezie',
                'prezzo' => 15.99,
                'is_visible' => true,
                'image' => 'Tandoori.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Chicken Tikka Masala',
                'descrizione' => 'Pezzi di pollo arrosto in una salsa cremosa di pomodoro e spezie.',
                'ingredienti' => 'Pollo, pomodoro, spezie',
                'prezzo' => 17.99,
                'is_visible' => true,
                'image' => 'Tikka.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Paneer Tikka',
                'descrizione' => 'Cubetti di paneer (formaggio indiano) marinati e grigliati.',
                'ingredienti' => 'Paneer, spezie, yogurt',
                'prezzo' => 14.49,
                'is_visible' => true,
                'image' => 'Paneer.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Biryani di Agnello',
                'descrizione' => "Un piatto di riso speziato con carne d'agnello, aromi e erbe.",
                'ingredienti' => 'Agnello, riso, spezie',
                'prezzo' => 19.99,
                'is_visible' => true,
                'image' => 'Biryani.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Samosa',
                'descrizione' => 'Frittelle ripiene di patate, piselli e spezie.',
                'ingredienti' => 'Patate, piselli, spezie',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'Samosa.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Dal Makhani',
                'descrizione' => 'Un piatto di lenticchie nere cotte lentamente in una salsa di pomodoro e spezie.',
                'ingredienti' => 'Lenticchie nere, pomodoro, spezie',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Dal.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Butter Chicken',
                'descrizione' => 'Pollo cotto in una salsa cremosa al burro e pomodoro.',
                'ingredienti' => 'Pollo, burro, pomodoro',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'Butter.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Aloo Gobi',
                'descrizione' => 'Un piatto vegetariano di patate e cavolfiore cotto con spezie.',
                'ingredienti' => 'Patate, cavolfiore, spezie',
                'prezzo' => 13.49,
                'is_visible' => true,
                'image' => 'Aloo.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Rogan Josh',
                'descrizione' => "Un curry ricco e speziato di carne d'agnello.",
                'ingredienti' => 'Agnello, spezie, yogurt',
                'prezzo' => 18.49,
                'is_visible' => true,
                'image' => 'Rogan.jpg',
                'restaurant_id' => 7,
            ],

            [
                'nome' => 'Gulab Jamun',
                'descrizione' => 'Palle di latte fritte in uno sciroppo dolce e profumato.',
                'ingredienti' => 'Latte, zucchero, cardamomo',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'Gulab.jpg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Paneer Tikka',
                'descrizione' => 'Antipasto indiano con cubetti di formaggio marinato e grigliato.',
                'ingredienti' => 'Formaggio paneer, spezie, yogurt',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'cibo-messicano.jpeg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Dolce al Mango',
                'descrizione' => 'Dolce tailandese con mango, riso glutinoso e latte di cocco.',
                'ingredienti' => 'Mango, riso glutinoso, latte di cocco',
                'prezzo' => 6.99,
                'is_visible' => true,
                'image' => 'piatto-indiano.jpg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Dal Makhani',
                'descrizione' => 'Piatto indiano a base di lenticchie nere e spezie.',
                'ingredienti' => 'Lenticchie nere, spezie, panna',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'cibo-indiano-lenticchie.jpeg',
                'restaurant_id' => 7,
            ],
            [
                'nome' => 'Misto di carne',
                'descrizione' => 'Fettina, sovracoscia, bombette e spiedini con contorno melanzane, zucchine, pomodori, sedano, noci e maionese.',
                'ingredienti' => 'Fettina, sovracoscia, bombette e spiedini',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'carne.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Risotto ai Funghi',
                'descrizione' => 'Piatto italiano con riso, funghi porcini e formaggio parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, formaggio parmigiano',
                'prezzo' => 35.99,
                'is_visible' => true,
                'image' => 'Risotto-ai-funghi.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Lasagna al Forno',
                'descrizione' => 'Uno strato di pasta al forno ricoperto di ricotta, carne macinata, pomodoro e formaggio fuso.',
                'ingredienti' => 'Pasta, carne macinata, ricotta, pomodoro, formaggio',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'lasagna.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Pizza Margherita',
                'descrizione' => 'Una pizza classica italiana con mozzarella, pomodoro e basilico.',
                'ingredienti' => 'Mozzarella, pomodoro, basilico',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'pizza_margherita.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Risotto ai Funghi Porcini',
                'descrizione' => 'Risotto cremoso preparato con funghi porcini freschi e parmigiano.',
                'ingredienti' => 'Riso, funghi porcini, brodo, parmigiano',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'risotto_funghi.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Penne alla Vodka',
                'descrizione' => 'Penne in una salsa cremosa a base di vodka, pomodoro e panna.',
                'ingredienti' => 'Penne, vodka, pomodoro, panna',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'penne_vodka.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Ossobuco alla Milanese',
                'descrizione' => 'Un piatto milanese tradizionale con stinco di vitello cotto in una salsa ricca.',
                'ingredienti' => 'Stinco di vitello, vino bianco, brodo, gremolata',
                'prezzo' => 24.99,
                'is_visible' => true,
                'image' => 'ossobuco.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tiramisù',
                'descrizione' => 'Un dolce italiano classico con biscotti savoiardi, caffè, mascarpone e cacao.',
                'ingredienti' => 'Savoiardi, caffè, mascarpone, cacao',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'tiramisu.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tagliatelle al Tartufo',
                'descrizione' => 'Tagliatelle fresche condite con una salsa al tartufo nero prelibata.',
                'ingredienti' => 'Tagliatelle, tartufo nero, panna, burro',
                'prezzo' => 19.99,
                'is_visible' => true,
                'image' => 'tagliatelle_tartufo.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Calamari Fritti',
                'descrizione' => 'Calamari freschi fritti in una crosta croccante, serviti con salsa al limone.',
                'ingredienti' => 'Calamari, farina, olio, limone',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'calamari_fritti.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Ravioli al Burro e Salvia',
                'descrizione' => 'Ravioli ripieni di ricotta e spinaci, conditi con burro fuso e salvia.',
                'ingredienti' => 'Ravioli, ricotta, spinaci, burro, salvia',
                'prezzo' => 15.99,
                'is_visible' => true,
                'image' => 'ravioli_burro_salvia.jpg',
                'restaurant_id' => 8,
            ],
            [
                'nome' => 'Tofu al Curry',
                'descrizione' => 'Piatto vegetariano con tofu, verdure e curry.',
                'ingredienti' => 'Tofu, verdure, curry',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'piatto-indiano.jpg',
                'restaurant_id' => 9,
            ],
            [
                'nome' => 'Insalata Waldorf',
                'descrizione' => 'Insalata classica con mele, sedano, noci e maionese.',
                'ingredienti' => 'Mele, sedano, noci, maionese',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'insalata.jpg',
                'restaurant_id' => 9,
            ],
            [
                'nome' => 'Insalata Caprese',
                'descrizione' => "Insalata fresca con pomodoro, mozzarella e basilico, condita con olio d'oliva.",
                'ingredienti' => "Pomodoro, mozzarella, basilico, olio d'oliva",
                'prezzo' => 12.49,
                'is_visible' => true,
                'image' => 'Caprese.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Pasta al Pesto',
                'descrizione' => "Pasta con salsa di basilico, pinoli, pecorino e olio d'oliva.",
                'ingredienti' => "Pasta, basilico, pinoli, pecorino, olio d'oliva",
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Pasta_Pesto.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Insalata Greca',
                'descrizione' => 'Insalata fresca con pomodoro, cetrioli, olive, cipolla rossa e formaggio feta.',
                'ingredienti' => 'Pomodoro, cetrioli, olive, cipolla rossa, formaggio feta',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'Greca.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Lasagne Vegetariane',
                'descrizione' => 'Strati di pasta con ricotta, spinaci, pomodoro e formaggio.',
                'ingredienti' => 'Pasta, ricotta, spinaci, pomodoro, formaggio',
                'prezzo' => 15.49,
                'is_visible' => true,
                'image' => 'Lasagne_Vegetariane.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Couscous alle Verdure',
                'descrizione' => 'Couscous con verdure arrostite e condito con spezie.',
                'ingredienti' => 'Couscous, verdure, spezie',
                'prezzo' => 13.49,
                'is_visible' => true,
                'image' => 'Couscous.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Hummus',
                'descrizione' => 'Una crema a base di ceci, tahini, limone e aglio, servita con pane pita.',
                'ingredienti' => 'Ceci, tahini, limone, aglio',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'Hummus.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Pad Thai Vegetariano',
                'descrizione' => 'Un piatto di noodle di riso saltati con verdure e tofu in una salsa agrodolce.',
                'ingredienti' => 'Noodle di riso, verdure, tofu, salsa agrodolce',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'Pad_Thai.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Tofu al Curry',
                'descrizione' => 'Tofu cubetti cotti in una salsa di curry cremosa con verdure.',
                'ingredienti' => 'Tofu, curry, verdure',
                'prezzo' => 16.49,
                'is_visible' => true,
                'image' => 'Tofu_Curry.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Insalata di Falafel',
                'descrizione' => 'Insalata mista con falafel (polpette di ceci fritte) e salsa tahini.',
                'ingredienti' => 'Ceci, tahini, insalata, falafel',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'Falafel_Salad.jpg',
                'restaurant_id' => 9,
            ],

            [
                'nome' => 'Risotto ai funghi',
                'descrizione' => 'Risotto cremoso con funghi porcini e prezzemolo.',
                'ingredienti' => 'Riso, funghi porcini, brodo, prezzemolo',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'Risotto.jpg',
                'restaurant_id' => 9,
            ],
            [
                'nome' => 'Sushi Vegano',
                'descrizione' => 'Assortimento di sushi vegano con avocado, cetriolo e pepe.',
                'ingredienti' => 'Avocado, cetriolo, pepe',
                'prezzo' => 15.99,
                'is_visible' => true,
                'image' => 'sushi.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Hamburger Vegetariano',
                'descrizione' => 'Hamburger vegetariano con pattina di ceci e verdure.',
                'ingredienti' => 'Pattina di ceci, verdure, pane vegano',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'hamburger-vegetariano.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Bowl di Quinoa e Verdure',
                'descrizione' => 'Un bowl salutare con quinoa, verdure miste, ceci e una vinaigrette al limone.',
                'ingredienti' => 'Quinoa, verdure miste, ceci, limone',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'bowl_quinoa.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Pizza Vegana ai Funghi',
                'descrizione' => 'Una pizza vegana con base di verdure, funghi misti, e formaggio vegano.',
                'ingredienti' => 'Base di verdure, funghi misti, formaggio vegano',
                'prezzo' => 14.99,
                'is_visible' => true,
                'image' => 'pizza_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Hamburger di Ceci',
                'descrizione' => 'Un hamburger a base di ceci con insalata, pomodoro e maionese vegana.',
                'ingredienti' => 'Ceci, insalata, pomodoro, maionese vegana',
                'prezzo' => 10.99,
                'is_visible' => true,
                'image' => 'hamburger_ceci.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Avocado e Lenticchie',
                'descrizione' => "Un'insalata fresca con avocado, lenticchie, cetrioli e un dressing al sesamo.",
                'ingredienti' => 'Avocado, lenticchie, cetrioli, dressing al sesamo',
                'prezzo' => 11.99,
                'is_visible' => true,
                'image' => 'insalata_avocado.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Pasta al Pesto di Basilico',
                'descrizione' => 'Pasta servita con un pesto cremoso a base di basilico, pinoli e lievito alimentare.',
                'ingredienti' => 'Pasta, pesto di basilico, pinoli, lievito alimentare',
                'prezzo' => 13.99,
                'is_visible' => true,
                'image' => 'pasta_pesto.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Quinoa e Avocado',
                'descrizione' => "Un'insalata leggera con quinoa, avocado, pomodori e olive nere.",
                'ingredienti' => 'Quinoa, avocado, pomodori, olive nere',
                'prezzo' => 9.99,
                'is_visible' => true,
                'image' => 'insalata_quinoa_avocado.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Risotto ai Funghi Porcini',
                'descrizione' => 'Risotto cremoso preparato con funghi porcini freschi e senza latticini.',
                'ingredienti' => 'Riso, funghi porcini, brodo vegetale',
                'prezzo' => 16.99,
                'is_visible' => true,
                'image' => 'risotto_funghi_vegano.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Tacos di Barbabietola',
                'descrizione' => 'Tacos gustosi con barbabietola arrostita, guacamole e salsa piccante.',
                'ingredienti' => 'Barbabietola, guacamole, salsa piccante, tortilla',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'tacos_barbabietola.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Zuppa di Lenticchie Rosse',
                'descrizione' => 'Una zuppa deliziosa a base di lenticchie rosse, pomodori e curry.',
                'ingredienti' => 'Lenticchie rosse, pomodori, curry',
                'prezzo' => 8.99,
                'is_visible' => true,
                'image' => 'zuppa_lenticchie_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Insalata di Frutta Fresca',
                'descrizione' => "Un'insalata rinfrescante con una varietà di frutta fresca e una spruzzata di limone.",
                'ingredienti' => 'Frutta mista, limone',
                'prezzo' => 7.99,
                'is_visible' => true,
                'image' => 'insalata_frutta_vegana.jpg',
                'restaurant_id' => 10,
            ],
            [
                'nome' => 'Curry Massaman',
                'descrizione' => 'Curry thailandese con carne, patate e arachidi.',
                'ingredienti' => 'Carne, patate, arachidi',
                'prezzo' => 12.99,
                'is_visible' => true,
                'image' => 'curry-indiano.jpeg',
                'restaurant_id' => 3,
            ],
        ];

        // Inserisce prodotti nell'array multidimensionale
        Product::insert($products);
    }
}
